[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.build]
cmds = ["go build -ldflags \"-X main.GitCommit=$RAILWAY_GIT_COMMIT_SHA\" -o out ."]

[deploy]
startCommand = "./out"
region = "asia-southeast1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
